/** สิทธิ์ทั้งหมดของระบบ — seed และ policy ใช้ชุดเดียวกัน */

export const PERMISSIONS = [
  { key: "patient:read", group: "patient", description: "ดูทะเบียนเจ้าของและสัตว์" },
  { key: "patient:write", group: "patient", description: "สร้าง/แก้ทะเบียนเจ้าของและสัตว์" },
  { key: "patient:merge", group: "patient", description: "รวมระเบียนซ้ำ" },
  { key: "patient:delete", group: "patient", description: "ลบระเบียน (soft delete)" },
  { key: "clinical:read", group: "clinical", description: "ดูเวชระเบียน" },
  { key: "clinical:write", group: "clinical", description: "บันทึก vital / SOAP / คำสั่ง" },
  { key: "clinical:sign", group: "clinical", description: "ลงนาม SOAP" },
  { key: "clinical:addendum", group: "clinical", description: "เพิ่ม addendum หลังลงนาม" },
  { key: "clinical:override_alert", group: "clinical", description: "ข้ามคำเตือนแพ้ยา" },
  { key: "pharmacy:prescribe", group: "pharmacy", description: "สั่งยา" },
  { key: "pharmacy:dispense", group: "pharmacy", description: "จ่ายยาและตัดสต็อก" },
  { key: "pharmacy:controlled_drug", group: "pharmacy", description: "ยาควบคุม" },
  { key: "scheduling:read", group: "scheduling", description: "ดูตารางนัด" },
  { key: "scheduling:write", group: "scheduling", description: "จอง/เลื่อน/ยกเลิกนัด" },
  { key: "scheduling:override_conflict", group: "scheduling", description: "จองทับโดยมีเหตุผล" },
  { key: "boarding:checkin", group: "boarding", description: "เช็คอินฝากเลี้ยง" },
  { key: "boarding:checkout", group: "boarding", description: "เช็คเอาท์ฝากเลี้ยง" },
  { key: "boarding:care_log", group: "boarding", description: "บันทึกดูแลรายวัน" },
  { key: "boarding:waive_vaccine", group: "boarding", description: "ข้ามตรวจวัคซีนก่อนรับฝาก" },
  { key: "grooming:read", group: "grooming", description: "ดูคิวกรูมมิ่ง" },
  { key: "grooming:write", group: "grooming", description: "บันทึกงานกรูมมิ่ง" },
  { key: "inventory:read", group: "inventory", description: "ดูสต็อก" },
  { key: "inventory:receive", group: "inventory", description: "รับของเข้าล็อต" },
  { key: "inventory:adjust", group: "inventory", description: "ปรับยอดสต็อก" },
  { key: "inventory:count_approve", group: "inventory", description: "อนุมัติผลตรวจนับ" },
  { key: "inventory:purchase_approve", group: "inventory", description: "อนุมัติใบสั่งซื้อ" },
  { key: "billing:read", group: "billing", description: "ดูบิลและค่าใช้จ่าย" },
  { key: "billing:charge", group: "billing", description: "ตั้งค่าใช้จ่าย" },
  { key: "billing:invoice", group: "billing", description: "ออกบิล/ใบเสร็จ" },
  { key: "billing:approve_discount", group: "billing", description: "อนุมัติส่วนลดเกินเพดาน" },
  { key: "billing:void_invoice", group: "billing", description: "ยกเลิกบิลที่ออกแล้ว" },
  { key: "billing:credit_note", group: "billing", description: "ออกใบลดหนี้" },
  { key: "billing:refund", group: "billing", description: "คืนเงิน" },
  { key: "cash:open_shift", group: "cash", description: "เปิดกะเงินสด" },
  { key: "cash:close_shift", group: "cash", description: "ปิดกะเงินสด" },
  { key: "cash:approve_variance", group: "cash", description: "อนุมัติผลต่างเงินสด" },
  { key: "report:branch", group: "report", description: "รายงานระดับสาขา" },
  { key: "report:tenant", group: "report", description: "รายงานข้ามสาขา" },
  { key: "report:financial", group: "report", description: "รายงานการเงิน" },
  { key: "report:export", group: "report", description: "ส่งออกข้อมูล" },
  { key: "admin:users", group: "admin", description: "จัดการผู้ใช้" },
  { key: "admin:roles", group: "admin", description: "จัดการบทบาท" },
  { key: "admin:catalog", group: "admin", description: "จัดการแค็ตตาล็อก" },
  { key: "admin:settings", group: "admin", description: "ตั้งค่าคลินิก" },
  { key: "admin:tax_profile", group: "admin", description: "ตั้งค่าภาษีของสาขา" },
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number]["key"];

export const SYSTEM_ROLES = [
  "RECEPTIONIST",
  "VET_TECH",
  "VET",
  "GROOMER",
  "BOARDING_STAFF",
  "PHARMACY",
  "CASHIER",
  "BRANCH_MANAGER",
  "OWNER_ADMIN",
  "PET_OWNER",
] as const;

export type SystemRoleKey = (typeof SYSTEM_ROLES)[number];

const ALL_KEYS = PERMISSIONS.map((p) => p.key);

const BRANCH_MANAGER_KEYS = ALL_KEYS.filter(
  (k) => k !== "report:tenant" && k !== "admin:tax_profile",
);

/** บทบาทสำเร็จรูป 9 แบบของพนักงาน + PET_OWNER สำหรับพอร์ทัล */
export const SYSTEM_ROLE_PERMISSIONS: Record<SystemRoleKey, readonly string[]> = {
  RECEPTIONIST: [
    "patient:read",
    "patient:write",
    "scheduling:read",
    "scheduling:write",
    "billing:read",
    "billing:charge",
    "billing:invoice",
    "cash:open_shift",
    "cash:close_shift",
    "grooming:read",
    "grooming:write",
    "boarding:checkin",
    "boarding:checkout",
  ],
  VET_TECH: [
    "patient:read",
    "clinical:read",
    "clinical:write",
    "pharmacy:dispense",
    "boarding:care_log",
    "boarding:checkin",
    "inventory:read",
  ],
  VET: [
    "patient:read",
    "patient:write",
    "clinical:read",
    "clinical:write",
    "clinical:sign",
    "clinical:addendum",
    "clinical:override_alert",
    "pharmacy:prescribe",
    "pharmacy:dispense",
    "pharmacy:controlled_drug",
    "scheduling:read",
    "scheduling:write",
    "boarding:checkin",
    "boarding:checkout",
    "boarding:care_log",
    "boarding:waive_vaccine",
    "inventory:read",
    "billing:read",
    "billing:charge",
  ],
  GROOMER: ["patient:read", "grooming:read", "grooming:write", "scheduling:read"],
  BOARDING_STAFF: [
    "patient:read",
    "boarding:checkin",
    "boarding:checkout",
    "boarding:care_log",
    "scheduling:read",
  ],
  PHARMACY: [
    "patient:read",
    "clinical:read",
    "pharmacy:dispense",
    "pharmacy:controlled_drug",
    "inventory:read",
    "inventory:receive",
    "inventory:adjust",
    "inventory:count_approve",
    "inventory:purchase_approve",
  ],
  CASHIER: [
    "patient:read",
    "billing:read",
    "billing:charge",
    "billing:invoice",
    "cash:open_shift",
    "cash:close_shift",
  ],
  BRANCH_MANAGER: BRANCH_MANAGER_KEYS,
  OWNER_ADMIN: ALL_KEYS,
  PET_OWNER: [],
};

export const SYSTEM_ROLE_NAMES: Record<SystemRoleKey, string> = {
  RECEPTIONIST: "เจ้าหน้าที่ต้อนรับ",
  VET_TECH: "ผู้ช่วยสัตวแพทย์",
  VET: "สัตวแพทย์",
  GROOMER: "ช่างกรูมมิ่ง",
  BOARDING_STAFF: "พนักงานฝากเลี้ยง",
  PHARMACY: "คลัง/เภสัช",
  CASHIER: "แคชเชียร์",
  BRANCH_MANAGER: "ผู้จัดการสาขา",
  OWNER_ADMIN: "เจ้าของคลินิก",
  PET_OWNER: "เจ้าของสัตว์",
};
